function myFunction() {
  document.getElementById("prop").style.display = "block";
  var cat, college, ip, percent, pr;
  college = {
    [99]: ["VJTI_MUMBAI", "COEP_PUNE", "BHARTIYA VIDYA BHAVAN'S SARDAR PATEL INSTITUTE OF TECHNOLOGY _ ANDHERI_ MUMBAI", "PICT_PUNE", "ICT_MUMBAI", "WALCHAND COLLEGE OF ENGINEERING_ SANGLI",
      "BANSILAL RAMNATH AGARAWAL CHARITABLE TRUST'S VISHWAKARMA INSTITUTE OF TECHNOLOGY_ BIBWEWADI_ PUNE", "PIMPRI CHINCHWAD EDUCATION TRUST_ PIMPRI CHINCHWAD COLLEGE OF ENGINEERING_ PUNE",
      "MKSSS'S CUMMINS COLLEGE OF ENGINEERING FOR WOMEN_ KARVENAGAR_PUNE", "B.R.A.C.T'S VISHWAKARMA INSTITUTE OF INFORMATION TECHNOLOGY_ KONDHWA (BK.)_ PUNE"
    ],
    [98]: ["WALCHAND COLLEGE OF ENGINEERING_ SANGLI", "BANSILAL RAMNATH AGARAWAL CHARITABLE TRUST'S VISHWAKARMA INSTITUTE OF TECHNOLOGY_ BIBWEWADI_ PUNE", "PIMPRI CHINCHWAD EDUCATION TRUST_ PIMPRI CHINCHWAD COLLEGE OF ENGINEERING_ PUNE",
      "MKSSS'S CUMMINS COLLEGE OF ENGINEERING FOR WOMEN_ KARVENAGAR_PUNE", "B.R.A.C.T'S VISHWAKARMA INSTITUTE OF INFORMATION TECHNOLOGY_ KONDHWA (BK.)_ PUNE",
      "PUNE VIDYARTHI GRIHA'S COLLEGE OF ENGINEERING AND TECHNOLOGY AND G K PATE(WANI) INSTITUTE OF MANAGEMENT_ PUNE", "GOVERNMENT COLLEGE OF ENGINEERING_ AURANGABAD", "GOVERNMENT COLLEGE OF ENGINEERING_ AMRAVATI",
      "GOVERNMENT COLLEGE OF ENGINEERING_ KARAD", "INTERNATIONAL INSTITUTE OF INFORMATION TECHNOLOGY (I\u00b2IT)_ PUNE.", "VIDYALANKAR INSTITUTE OF TECHNOLOGY_WADALA_ MUMBAI"
    ],
    [97]: ["PIMPRI CHINCHWAD EDUCATION TRUST_ PIMPRI CHINCHWAD COLLEGE OF ENGINEERING_ PUNE", "MKSSS'S CUMMINS COLLEGE OF ENGINEERING FOR WOMEN_ KARVENAGAR_PUNE",
      "B.R.A.C.T'S VISHWAKARMA INSTITUTE OF INFORMATION TECHNOLOGY_ KONDHWA (BK.)_ PUNE", "PUNE VIDYARTHI GRIHA'S COLLEGE OF ENGINEERING AND TECHNOLOGY AND G K PATE(WANI) INSTITUTE OF MANAGEMENT_ PUNE",
      "GOVERNMENT COLLEGE OF ENGINEERING_ AURANGABAD", "GOVERNMENT COLLEGE OF ENGINEERING_ AMRAVATI", "GOVERNMENT COLLEGE OF ENGINEERING_ KARAD", "INTERNATIONAL INSTITUTE OF INFORMATION TECHNOLOGY (I\u00b2IT)_ PUNE.",
      "VIDYALANKAR INSTITUTE OF TECHNOLOGY_WADALA_ MUMBAI", "SHRI GURU GOBIND SINGHJI INSTITUTE OF ENGINEERING AND TECHNOLOGY_ NANDED", "MIT ACADEMY OF ENGINEERING_ALANDI_ PUNE"
    ],
    [96]: ["PUNE VIDYARTHI GRIHA'S COLLEGE OF ENGINEERING AND TECHNOLOGY AND G K PATE(WANI) INSTITUTE OF MANAGEMENT_ PUNE", "GOVERNMENT COLLEGE OF ENGINEERING_ AURANGABAD", "GOVERNMENT COLLEGE OF ENGINEERING_ AMRAVATI",
      "GOVERNMENT COLLEGE OF ENGINEERING_ KARAD", "INTERNATIONAL INSTITUTE OF INFORMATION TECHNOLOGY (I\u00b2IT)_ PUNE.", "VIDYALANKAR INSTITUTE OF TECHNOLOGY_WADALA_ MUMBAI",
      "SHRI GURU GOBIND SINGHJI INSTITUTE OF ENGINEERING AND TECHNOLOGY_ NANDED", "MIT ACADEMY OF ENGINEERING_ALANDI_ PUNE", "ALL INDIA SHRI SHIVAJI MEMORIAL SOCIETY'S COLLEGE OF ENGINEERING_ PUNE",
      "GOVERNMENT COLLEGE OF ENGINEERING_ NAGPUR", "DR. D. Y. PATIL PRATISHTHAN'S D.Y.PATIL COLLEGE OF ENGINEERING AKURDI_ PUNE"
    ],
    [95]: ["INTERNATIONAL INSTITUTE OF INFORMATION TECHNOLOGY (I\u00b2IT)_ PUNE.", "VIDYALANKAR INSTITUTE OF TECHNOLOGY_WADALA_ MUMBAI", "SHRI GURU GOBIND SINGHJI INSTITUTE OF ENGINEERING AND TECHNOLOGY_ NANDED",
      "MIT ACADEMY OF ENGINEERING_ALANDI_ PUNE", "ALL INDIA SHRI SHIVAJI MEMORIAL SOCIETY'S COLLEGE OF ENGINEERING_ PUNE", "GOVERNMENT COLLEGE OF ENGINEERING_ NAGPUR",
      "DR. D. Y. PATIL PRATISHTHAN'S D.Y.PATIL COLLEGE OF ENGINEERING AKURDI_ PUNE", "MANJARA CHARITABLE TRUST'S RAJIV GANDHI INSTITUTE OF TECHNOLOGY_ MUMBAI", "GOVERNMENT COLLEGE OF ENGINEERING & RESEARCH_ AVASARI KHURD",
      "JAYWANT SHIKSHAN PRASARAK MANDAL'S_RAJARSHI SHAHU COLLEGE OF ENGINEERING_ TATHAWADE_ PUNE", "PROGRESSIVE EDUCATION SOCIETY'S MODERN COLLEGE OF ENGINEERING_ PUNE"
    ],
    [94]: ["GOVERNMENT COLLEGE OF ENGINEERING_ NAGPUR", "DR. D. Y. PATIL PRATISHTHAN'S D.Y.PATIL COLLEGE OF ENGINEERING AKURDI_ PUNE", "MANJARA CHARITABLE TRUST'S RAJIV GANDHI INSTITUTE OF TECHNOLOGY_ MUMBAI",
      "GOVERNMENT COLLEGE OF ENGINEERING & RESEARCH_ AVASARI KHURD", "JAYWANT SHIKSHAN PRASARAK MANDAL'S_RAJARSHI SHAHU COLLEGE OF ENGINEERING_ TATHAWADE_ PUNE", "PROGRESSIVE EDUCATION SOCIETY'S MODERN COLLEGE OF ENGINEERING_ PUNE",
      "MARATHWADA MITRA MANDAL'S COLLEGE OF ENGINEERING_ KARVENAGAR_ PUNE", "K. K. WAGH INSTITUTE OF ENGINEERING EDUCATION AND RESEARCH_ NASHIK", "SINHGAD COLLEGE OF ENGINEERING_ VADGAON (BK)_ PUNE",
      "VIDYAVARDHINI'S COLLEGE OF ENGINEERING AND TECHNOLOGY_ VASAI", "GOVERNMENT COLLEGE OF ENGINEERING_ JALGAON"
    ],
    [93]: ["MANJARA CHARITABLE TRUST'S RAJIV GANDHI INSTITUTE OF TECHNOLOGY_ MUMBAI", "GOVERNMENT COLLEGE OF ENGINEERING & RESEARCH_ AVASARI KHURD", "JAYWANT SHIKSHAN PRASARAK MANDAL'S_RAJARSHI SHAHU COLLEGE OF ENGINEERING_ TATHAWADE_ PUNE",
      "PROGRESSIVE EDUCATION SOCIETY'S MODERN COLLEGE OF ENGINEERING_ PUNE", "MARATHWADA MITRA MANDAL'S COLLEGE OF ENGINEERING_ KARVENAGAR_ PUNE", "K. K. WAGH INSTITUTE OF ENGINEERING EDUCATION AND RESEARCH_ NASHIK",
      "SINHGAD COLLEGE OF ENGINEERING_ VADGAON (BK)_ PUNE", "VIDYAVARDHINI'S COLLEGE OF ENGINEERING AND TECHNOLOGY_ VASAI", "GOVERNMENT COLLEGE OF ENGINEERING_ JALGAON", "YESHWANTRAO CHAVAN COLLEGE OF ENGINEERING_WANADONGRI_ NAGPUR",
      "BHARATI VIDYAPEETH COLLEGE OF ENGINEERING_ NAVI MUMBAI"
    ],
    [92]: ["SINHGAD COLLEGE OF ENGINEERING_ VADGAON (BK)_ PUNE", "VIDYAVARDHINI'S COLLEGE OF ENGINEERING AND TECHNOLOGY_ VASAI", "GOVERNMENT COLLEGE OF ENGINEERING_ JALGAON", "YESHWANTRAO CHAVAN COLLEGE OF ENGINEERING_WANADONGRI_ NAGPUR",
      "BHARATI VIDYAPEETH COLLEGE OF ENGINEERING_ NAVI MUMBAI", "ATHARVA COLLEGE OF ENGINEERING_MALAD(WEST)_MUMBAI", "K. E. SOCIETY'S RAJARAMBAPU INSTITUTE OF TECHNOLOGY_ WALWA_ SANGLI",
      "N.Y.S.S.'S DATTA MEGHE COLLEGE OF ENGINEERING_ AIROLI_ NAVI MUMBAI", "TERNA ENGINEERING COLLEGE_ NERUL_ NAVI MUMBAI", "DR. D.Y.PATIL INSTITUTE OF ENGINEERING_ MANAGEMENT & RESEACH_ AKURDI_ PUNE",
      "DR. D. Y. PATIL VIDYA PRATISHTHAN SOCIETY\u2019S DR. D. Y. PATIL INSTITUTE OF TECHNOLOGY_ PIMPRI_ PUNE"
    ],
    [91]: ["BHARATI VIDYAPEETH COLLEGE OF ENGINEERING_ NAVI MUMBAI", "ATHARVA COLLEGE OF ENGINEERING_MALAD(WEST)_MUMBAI", "K. E. SOCIETY'S RAJARAMBAPU INSTITUTE OF TECHNOLOGY_ WALWA_ SANGLI",
      "N.Y.S.S.'S DATTA MEGHE COLLEGE OF ENGINEERING_ AIROLI_ NAVI MUMBAI", "TERNA ENGINEERING COLLEGE_ NERUL_ NAVI MUMBAI", "DR. D.Y.PATIL INSTITUTE OF ENGINEERING_ MANAGEMENT & RESEACH_ AKURDI_ PUNE",
      "DR. D. Y. PATIL VIDYA PRATISHTHAN SOCIETY\u2019S DR. D. Y. PATIL INSTITUTE OF TECHNOLOGY_ PIMPRI_ PUNE", "DR. BABASAHEB AMBEDKAR TECHNOLOGICAL UNIVERSITY_ LONERE",
      "USHA MITTAL INSTITUTE OF TECHNOLOGY SNDT WOMEN'S UNIVERSITY_ MUMBAI",
      "WALCHAND INSTITUTE OF TECHNOLOGY_ SOLAPUR", "SHRI SANT GAJANAN MAHARAJ COLLEGE OF ENGINEERING_SHEGAON"
    ],
    [90]: ["K. E. SOCIETY'S RAJARAMBAPU INSTITUTE OF TECHNOLOGY_ WALWA_ SANGLI", "N.Y.S.S.'S DATTA MEGHE COLLEGE OF ENGINEERING_ AIROLI_ NAVI MUMBAI", "TERNA ENGINEERING COLLEGE_ NERUL_ NAVI MUMBAI",
      "DR. D.Y.PATIL INSTITUTE OF ENGINEERING_ MANAGEMENT & RESEACH_ AKURDI_ PUNE", "DR. D. Y. PATIL VIDYA PRATISHTHAN SOCIETY\u2019S DR. D. Y. PATIL INSTITUTE OF TECHNOLOGY_ PIMPRI_ PUNE",
      "DR. BABASAHEB AMBEDKAR TECHNOLOGICAL UNIVERSITY_ LONERE", "USHA MITTAL INSTITUTE OF TECHNOLOGY SNDT WOMEN'S UNIVERSITY_ MUMBAI", "WALCHAND INSTITUTE OF TECHNOLOGY_ SOLAPUR", "SHRI SANT GAJANAN MAHARAJ COLLEGE OF ENGINEERING_SHEGAON",
      "MODERN EDUCATION SOCIETY'S COLLEGE OF ENGINEERING_ PUNE", "BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE"
    ],
    [89]: ["DR. D. Y. PATIL VIDYA PRATISHTHAN SOCIETY\u2019S DR. D. Y. PATIL INSTITUTE OF TECHNOLOGY_ PIMPRI_ PUNE", "DR. BABASAHEB AMBEDKAR TECHNOLOGICAL UNIVERSITY_ LONERE",
      "USHA MITTAL INSTITUTE OF TECHNOLOGY SNDT WOMEN'S UNIVERSITY_ MUMBAI", "WALCHAND INSTITUTE OF TECHNOLOGY_ SOLAPUR", "SHRI SANT GAJANAN MAHARAJ COLLEGE OF ENGINEERING_SHEGAON", "MODERN EDUCATION SOCIETY'S COLLEGE OF ENGINEERING_ PUNE",
      "BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE", "MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING_ NASHIK",
      "DATTAJIRAO KADAM TECHNICAL EDUCATION SOCIETY'S TEXTILE & ENGINEERING INSTITUTE_ ICHALKARANJI.", "AMRUTVAHINI SHETI & SHIKSHAN VIKAS SANSTHA'S AMRUTVAHINI COLLEGE OF ENGINEERING_ SANGAMNER",
      "VASANTDADA PATIL PRATISHTHAN'S COLLEGE OF ENGINEERING AND VISUAL ARTS_ SION_ MUMBAI"
    ],
    [88]: ["BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE", "MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING_ NASHIK",
      "DATTAJIRAO KADAM TECHNICAL EDUCATION SOCIETY'S TEXTILE & ENGINEERING INSTITUTE_ ICHALKARANJI.", "AMRUTVAHINI SHETI & SHIKSHAN VIKAS SANSTHA'S AMRUTVAHINI COLLEGE OF ENGINEERING_ SANGAMNER",
      "VASANTDADA PATIL PRATISHTHAN'S COLLEGE OF ENGINEERING AND VISUAL ARTS_ SION_ MUMBAI", "SMT. INDIRA GANDHI COLLEGE OF ENGINEERING_ NAVI MUMBAI",
      "SINHGAD TECHNICAL EDUCATION SOCIETY'S SMT. KASHIBAI NAVALE COLLEGE OF ENGINEERING_VADGAON_PUNE", "VIDYA PRATISHTHAN'S KAMALNAYAN BAJAJ INSTITUTE OF ENGINEERING & TECHNOLOGY_ BARAMATI DIST.PUNE",
      "SARASWATI EDUCATION SOCIETY'S SARASWATI COLLEGE OF ENGINEERING_KHARGHAR NAVI MUMBAI", "SANJIVANI RURAL EDUCATION SOCIETY'S SANJIVANI COLLEGE OF ENGINEERING_ KOPARGAON"
    ],
    [87]: ["BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE", "MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING_ NASHIK",
      "DATTAJIRAO KADAM TECHNICAL EDUCATION SOCIETY'S TEXTILE & ENGINEERING INSTITUTE_ ICHALKARANJI.", "AMRUTVAHINI SHETI & SHIKSHAN VIKAS SANSTHA'S AMRUTVAHINI COLLEGE OF ENGINEERING_ SANGAMNER",
      "VASANTDADA PATIL PRATISHTHAN'S COLLEGE OF ENGINEERING AND VISUAL ARTS_ SION_ MUMBAI", "SMT. INDIRA GANDHI COLLEGE OF ENGINEERING_ NAVI MUMBAI",
      "SINHGAD TECHNICAL EDUCATION SOCIETY'S SMT. KASHIBAI NAVALE COLLEGE OF ENGINEERING_VADGAON_PUNE", "VIDYA PRATISHTHAN'S KAMALNAYAN BAJAJ INSTITUTE OF ENGINEERING & TECHNOLOGY_ BARAMATI DIST.PUNE",
      "SARASWATI EDUCATION SOCIETY'S SARASWATI COLLEGE OF ENGINEERING_KHARGHAR NAVI MUMBAI", "SANJIVANI RURAL EDUCATION SOCIETY'S SANJIVANI COLLEGE OF ENGINEERING_ KOPARGAON"
    ],
    [86]: ["BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE", "MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING_ NASHIK",
      "DATTAJIRAO KADAM TECHNICAL EDUCATION SOCIETY'S TEXTILE & ENGINEERING INSTITUTE_ ICHALKARANJI.", "AMRUTVAHINI SHETI & SHIKSHAN VIKAS SANSTHA'S AMRUTVAHINI COLLEGE OF ENGINEERING_ SANGAMNER",
      "VASANTDADA PATIL PRATISHTHAN'S COLLEGE OF ENGINEERING AND VISUAL ARTS_ SION_ MUMBAI", "SMT. INDIRA GANDHI COLLEGE OF ENGINEERING_ NAVI MUMBAI",
      "SINHGAD TECHNICAL EDUCATION SOCIETY'S SMT. KASHIBAI NAVALE COLLEGE OF ENGINEERING_VADGAON_PUNE", "VIDYA PRATISHTHAN'S KAMALNAYAN BAJAJ INSTITUTE OF ENGINEERING & TECHNOLOGY_ BARAMATI DIST.PUNE",
      "SARASWATI EDUCATION SOCIETY'S SARASWATI COLLEGE OF ENGINEERING_KHARGHAR NAVI MUMBAI", "SANJIVANI RURAL EDUCATION SOCIETY'S SANJIVANI COLLEGE OF ENGINEERING_ KOPARGAON"
    ],
    [85]: ["BHARATI VIDYAPEETH'S COLLEGE OF ENGINEERING_LAVALE_ PUNE", "MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING_ NASHIK",
      "DATTAJIRAO KADAM TECHNICAL EDUCATION SOCIETY'S TEXTILE & ENGINEERING INSTITUTE_ ICHALKARANJI.", "AMRUTVAHINI SHETI & SHIKSHAN VIKAS SANSTHA'S AMRUTVAHINI COLLEGE OF ENGINEERING_ SANGAMNER",
      "VASANTDADA PATIL PRATISHTHAN'S COLLEGE OF ENGINEERING AND VISUAL ARTS_ SION_ MUMBAI", "SMT. INDIRA GANDHI COLLEGE OF ENGINEERING_ NAVI MUMBAI",
      "SINHGAD TECHNICAL EDUCATION SOCIETY'S SMT. KASHIBAI NAVALE COLLEGE OF ENGINEERING_VADGAON_PUNE", "VIDYA PRATISHTHAN'S KAMALNAYAN BAJAJ INSTITUTE OF ENGINEERING & TECHNOLOGY_ BARAMATI DIST.PUNE",
      "SARASWATI EDUCATION SOCIETY'S SARASWATI COLLEGE OF ENGINEERING_KHARGHAR NAVI MUMBAI", "SANJIVANI RURAL EDUCATION SOCIETY'S SANJIVANI COLLEGE OF ENGINEERING_ KOPARGAON"
    ]
  };
  percent = Number.parseFloat(document.getElementById("myText").value);
  ip = Number.parseInt(percent);
  document.getElementById("college_3").innerHTML = college[ip][0];
  document.getElementById("college_1").innerHTML = college[ip][1];
  document.getElementById("college_2").innerHTML = college[ip][2];
  document.getElementById("college_4").innerHTML = college[ip][3];
  document.getElementById("college_5").innerHTML = college[ip][4];
  document.getElementById("college_6").innerHTML = college[ip][5];
  document.getElementById("college_7").innerHTML = college[ip][6];
  document.getElementById("college_8").innerHTML = college[ip][7];
  document.getElementById("college_9").innerHTML = college[ip][8];
  document.getElementById("college_10").innerHTML = college[ip][9];
  document.getElementById("college_11").innerHTML = college[ip][10];
  document.getElementById("college_12").innerHTML = college[ip][11];
  document.getElementById("college_13").innerHTML = college[ip][12];
  document.getElementById("college_14").innerHTML = college[ip][13];
  document.getElementById("college_15").innerHTML = college[ip][14];

}

function navbar() {
  var x = document.getElementById("navbar");
  var y = document.getElementsByClassName("navtab__link");
  var z = document.getElementById("navtab__login")
  var burger = document.getElementById("Burger")
  if (x.className === "navtab center-container") {
    x.className += ' responsivenav';
    for (j of y) {
      j.style.display = "block"

    }
    z.style.display = "block";

  } else {
    x.className = "navtab center-container";
    for (j of y) {
      j.style.display = "none"
    }
    z.style.display = "none"
  }


}
